Jonnitto:
  OpenStreetMap:
    defaultCountry: CH # ISO-Code from country
    colorShift: null # null, grayscale or dark
    colorShiftPreviewPattern: 'resource://Jonnitto.OpenStreetMap/Public/Assets/colorShift-%s.png'
    aspectRatio: '16 / 9' # Please use the official CSS syntax: https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio
    settings:
      pinColor: '#009fe3'
      tiles:
        url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
        options:
          attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          detectRetina: true

      # Example for stadiamaps
      # tiles:
      #   url: https://tiles.stadiamaps.com/tiles/alidade_smooth/{z}/{x}/{y}{r}.png'
      #   options:
      #     attribution: '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a>, &copy; <a href="https://openmaptiles.org/">OpenMapTiles</a> &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors'

      mapOptions:
        scrollWheelZoom: false
        # minZoom: 2
        # maxZoom: 18
